# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a8d5d0cfb659f7414ca7042f03c29d6746523fc9958e916df98530cd95299b8dc717b7798ebf9bf0548ae62429086d240ad4a6dc3c97926948cd1b6a7694884
  secret_email_pw: GAandrew31

test:
  secret_key_base: 5a2477dc8a7fe9c707df697eddff31485d2fc32b6d4fc492b315ed5048a3796a008ceeb8a0b64d371cc3d47ae1b9619f979941a96a9b5afde7c98b4324d95d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
